services:
  message-proxy:
    container_name: messageProxy
    build:
      context: .
      args:
        - BUILD_CONTEXT=messageProxy
      target: messageProxy
    ports:
      - "3000:3000"
    networks:
      - a-la-fois-network

  doc-handler:
    container_name: docHandler
    build:
      context: .
      args:
        - BUILD_CONTEXT=docHandler
      target: docHandler
    ports:
      - "3001:3000"
    networks:
      - a-la-fois-network

  redis:
    image: redis:7.0.2-alpine
    ports:
      - "6379:6379"

networks:
  a-la-fois-network: