services:
  message-proxy-1:
    container_name: messageProxy1
    depends_on:
      - kafka
    build:
      context: .
      args:
        - BUILD_CONTEXT=messageProxy
      target: messageProxy
    ports:
      - "3000:3000"
    networks:
      - kafka-network

  message-proxy-2:
    container_name: messageProxy2
    depends_on:
      - kafka
    build:
      context: .
      args:
        - BUILD_CONTEXT=messageProxy
      target: messageProxy
    ports:
      - "3001:3000"
    networks:
      - kafka-network

#  redis:
#    container_name: redis
#    image: redis:7.0.2-alpine
#    ports:
#      - "6379:6379"
#    networks:
#      - a-la-fois-network

  doc-handler:
    container_name: docHandler
    build:
      context: .
      args:
        - BUILD_CONTEXT=docHandler
      target: docHandler
    networks:
      - a-la-fois-network

  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - kafka-network

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - kafka-network

networks:
  kafka-network: